import type { DialogueTone, NpcProgress } from './types'

export interface RelationshipEvent {
  id: string
  npcId: string
  track: 'friendship' | 'romance'
  threshold: number
  title: string
  summary: string
  tone: DialogueTone
  lines: readonly string[]
}

const EVENT_ILLUSTRATIONS: Record<
  string,
  Record<RelationshipEvent['track'], string>
> = {
  shendu: {
    friendship: 'art/events/shendu-friendship-v1.webp',
    romance: 'art/events/shendu-romance-v1.webp',
  },
  guwan: {
    friendship: 'art/events/guwan-friendship-v1.webp',
    romance: 'art/events/guwan-romance-v1.webp',
  },
  taotao: {
    friendship: 'art/events/taotao-friendship-v2.webp',
    romance: 'art/events/taotao-romance-v2.webp',
  },
  qinghe: {
    friendship: 'art/events/qinghe-friendship-v1.webp',
    romance: 'art/events/qinghe-romance-v1.webp',
  },
  jiangxiaoman: {
    friendship: 'art/events/jiangxiaoman-friendship-v1.webp',
    romance: 'art/events/jiangxiaoman-romance-v1.webp',
  },
  chenshi: {
    friendship: 'art/events/chenshi-friendship-v1.webp',
    romance: 'art/events/chenshi-romance-v1.webp',
  },
  linchu: {
    friendship: 'art/events/linchu-friendship-v1.webp',
    romance: 'art/events/linchu-romance-v1.webp',
  },
  baizhi: {
    friendship: 'art/events/baizhi-friendship-v1.webp',
    romance: 'art/events/baizhi-romance-v1.webp',
  },
  suweiming: {
    friendship: 'art/events/suweiming-friendship-v1.webp',
    romance: 'art/events/suweiming-romance-v1.webp',
  },
  yueqingshan: {
    friendship: 'art/events/yueqingshan-friendship-v1.webp',
    romance: 'art/events/yueqingshan-romance-v1.webp',
  },
  wenjiu: {
    friendship: 'art/events/wenjiu-friendship-v1.webp',
    romance: 'art/events/wenjiu-romance-v1.webp',
  },
  hedeng: {
    friendship: 'art/events/hedeng-friendship-v1.webp',
    romance: 'art/events/hedeng-romance-v1.webp',
  },
}

export const RELATIONSHIP_EVENTS: readonly RelationshipEvent[] = [
  {
    id: 'shendu-f1-riverbank',
    npcId: 'shendu',
    track: 'friendship',
    threshold: 20,
    title: '五文钱',
    summary: '有人嫌贵，有人想赊。价钱没变。',
    tone: 'neutral',
    lines: [
      '岸边有人跟沈渡扯价钱，说五文太贵，又说下次结。沈渡靠着竹篙，不接话。',
      '“渡河五文钱。”对方再嚷，他只又说一遍，“对，还是五文钱。”',
    ],
  },
  {
    id: 'shendu-f2-old-rope',
    npcId: 'shendu',
    track: 'friendship',
    threshold: 50,
    title: '凫水',
    summary: '半夜有人凫水，他去逮人。天亮跟你抱怨两句。',
    tone: 'annoyed',
    lines: [
      '沈渡眼下发青，竹篙还挂着水草。你问他夜里干嘛去了。',
      '“那狗娃又带着一帮娃子凫水。给我逮个正着。”他说完打了个哈欠，“坐。”',
    ],
  },
  {
    id: 'shendu-f3-return-lamp',
    npcId: 'shendu',
    track: 'friendship',
    threshold: 90,
    title: '破桥',
    summary: '破桥拖了很久。林初终于来了。',
    tone: 'warm',
    lines: [
      '沈渡盯着河上那截烂板，念叨了好几天：那破桥什么时候能修一下。你把话捎给了林初。',
      '几天后他看见人影，只说一句：“林初终于来修栈桥了。”然后递你一块姜，没再说别的。',
    ],
  },
  {
    id: 'shendu-r1-shared-boat',
    npcId: 'shendu',
    track: 'romance',
    threshold: 30,
    title: '泡脚',
    summary: '水烧好了。他让你泡完再睡。',
    tone: 'warm',
    lines: [
      '夜里回屋，盆已经摆好，水还冒着热气。沈渡坐在凳子上搓绳子，不抬头。',
      '“水烧好了，泡了脚再睡吧。”你坐下，他才又低声补一句，“别烫着。”',
    ],
  },
  {
    id: 'shendu-r2-rain-sleeve',
    npcId: 'shendu',
    track: 'romance',
    threshold: 70,
    title: '漏雨',
    summary: '他家屋顶漏了。问你有没有空房间。',
    tone: 'shy',
    lines: [
      '下着雨。沈渡站在檐下，蓑衣湿了一角。他先说了声“早”，又卡住。',
      '“我..我家的屋顶漏水了。不知道你还有没有空房间？”说完他盯着地面，像在等渡船靠岸。',
    ],
  },
  {
    id: 'shendu-r3-homeward',
    npcId: 'shendu',
    track: 'romance',
    threshold: 120,
    title: '蓑衣',
    summary: '他答应搬来。先问蓑衣挂哪儿。',
    tone: 'warm',
    lines: [
      '雨停后你帮他把蓑衣从篱上收进来。沈渡进门，看见蓑衣已经挂好，愣了一下。',
      '“好。”他放下包，“蓑衣挂哪儿？……哦，挂那儿就行。”',
    ],
  },
  {
    id: 'qinghe-f1-diseased-seedlings',
    npcId: 'qinghe',
    track: 'friendship',
    threshold: 20,
    title: '焦黄',
    summary: '苗焦了。她唉哟半天，最后还是让你帮把手。',
    tone: 'worried',
    lines: [
      '青禾蹲在畦边，手指搓着一片焦叶：“唉哟我的苗苗哟，怎么焦黄焦黄的了。”',
      '你刚想安慰，她已经把竹耙塞过来：“咋咋呼呼啥。别傻站着，帮把手。”',
    ],
  },
  {
    id: 'qinghe-f2-seed-lesson',
    npcId: 'qinghe',
    track: 'friendship',
    threshold: 50,
    title: '老张头',
    summary: '水渠的旧账翻出来。她边骂边瞅着东边那块地。',
    tone: 'annoyed',
    lines: [
      '青禾指着水渠缺口跟你数落：“前年老张头偷偷切我的水渠，我跟他打了好久。今年我天天瞅着！”',
      '东边地里老张头正种豆角。她哼一声：“都没翻翻土，我看他能收上来个啥。走，咱们通沟去。”',
    ],
  },
  {
    id: 'qinghe-f3-long-lease',
    npcId: 'qinghe',
    track: 'friendship',
    threshold: 90,
    title: '杂草',
    summary: '她教你认叶子。说完又嫌你磨叽，自己先拔了。',
    tone: 'warm',
    lines: [
      '青禾捏着一片叶子放到你眼前：“你看，杂草的叶子是这样的。别记错了。”',
      '你刚点头，她已经蹲下去拔：“磨磨唧唧，边儿去，我来弄。——诶你别走，下一株还得你认。”',
    ],
  },
  {
    id: 'qinghe-r1-overnight-answer',
    npcId: 'qinghe',
    track: 'romance',
    threshold: 30,
    title: '稀罕',
    summary: '日头毒。她赶你回屋，话却说漏了。',
    tone: 'shy',
    lines: [
      '田埂上青禾把水袋往你手里一塞：“今天日头毒，你快回屋喝水吧。”',
      '你没立刻走。她挠了挠脸，声音突然小了：“我也稀罕你。听见没有？听见就快走，别晒坏了。”',
    ],
  },
  {
    id: 'qinghe-r2-empty-ridge',
    npcId: 'qinghe',
    track: 'romance',
    threshold: 70,
    title: '分着吃',
    summary: '麦香饼来了。她掰开，非要你吃一半。',
    tone: 'warm',
    lines: [
      '你把麦香饼递给她。青禾眼睛一亮：“这个好！”掰成两半就往你嘴里塞。',
      '“给，咱俩分着吃。”她自己那半已经咬了一口，“其实你干活也挺利索的。我就是闲不住。”',
    ],
  },
  {
    id: 'qinghe-r3-two-plans',
    npcId: 'qinghe',
    track: 'romance',
    threshold: 120,
    title: '菜圃',
    summary: '她答应搬来。第一件事是归置菜圃，锄头先找不见了。',
    tone: 'warm',
    lines: [
      '青禾拍拍手上的土，嘿嘿笑：“放着我来。以后家里菜圃给你归置得齐齐整整的。”',
      '进门她就往院角冲，半晌又探出头来：“谁把我锄头拿走了？？……哦，在你脚边。边儿去，我先翻土。”',
    ],
  },
  {
    id: 'guwan-f1-half-umbrella',
    npcId: 'guwan',
    track: 'friendship',
    threshold: 20,
    title: '扯皮',
    summary: '村头两家又吵。他发誓下回再不给他们量了。',
    tone: 'annoyed',
    lines: [
      '村头又传来吵架声。顾晚把尺一卷：“又在那扯皮。下回再不给他们量了。”',
      '你问界桩呢。他翻了个白眼：“谁把界桩给偷走了？？……我就是个照章办事的，整得左右不是人。”',
    ],
  },
  {
    id: 'guwan-f2-dry-firewood',
    npcId: 'guwan',
    track: 'friendship',
    threshold: 50,
    title: '南山',
    summary: '去南山测绘，走错三次，脚底打泡。',
    tone: 'neutral',
    lines: [
      '顾晚一瘸一拐进院，伞往边上一扔：“别提了，昨天去南山测绘，走错三次！脚底都打泡了。”',
      '他展开包袱给你看：“这是标尺，这是墨线，这半个馍馍是早上吃剩下的。——你笑什么，分你一半。”',
    ],
  },
  {
    id: 'guwan-f3-kept-seat',
    npcId: 'guwan',
    track: 'friendship',
    threshold: 90,
    title: '画像',
    summary: '他要给你画一张。指挥半天，自己先不好意思。',
    tone: 'warm',
    lines: [
      '顾晚夹着纸笔过来：“脸再往右转一点，对对，马上就画好了。”',
      '画到一半他忽然停住：“我很爱挑刺儿吗？……对不起啊。你别动！墨还没干。”',
    ],
  },
  {
    id: 'guwan-r1-taken-seriously',
    npcId: 'guwan',
    track: 'romance',
    threshold: 30,
    title: '听见了',
    summary: '你说完。他只回了三个字。',
    tone: 'shy',
    lines: [
      '你把话说清楚了。顾晚盯着伞骨，好一会儿没接。',
      '“我听见了。”他说完就往外走，走到门口又回头，“晚上吃啥？……我请。”',
    ],
  },
  {
    id: 'guwan-r2-closer-side',
    npcId: 'guwan',
    track: 'romance',
    threshold: 70,
    title: '栗子',
    summary: '糖炒栗子一递过去，他立刻护住，不许你收回。',
    tone: 'warm',
    lines: [
      '你掏出糖炒栗子。顾晚眼睛一亮：“哪儿来的栗子？别别别，别拿走，我喜欢我喜欢。”',
      '他塞了一颗到你手里：“我这人最不爱欠人情。——这颗不算欠。吃。”',
    ],
  },
  {
    id: 'guwan-r3-spare-key',
    npcId: 'guwan',
    track: 'romance',
    threshold: 120,
    title: '向阳',
    summary: '他答应搬来。先问住哪屋，只要向阳。',
    tone: 'warm',
    lines: [
      '顾晚点点头：“行，我住哪屋？……我得要一间向阳的房。”',
      '进屋第一件事是把图塞进柜子：“窗边潮，放柜子里。你那脏手也不洗洗再来翻我的书！——开玩笑的。有一点认真。”',
    ],
  },
  {
    id: 'jiangxiaoman-f1-salty-pot',
    npcId: 'jiangxiaoman',
    track: 'friendship',
    threshold: 20,
    title: '盐放多了',
    summary: '汤咸了。她先慌，又说加点醋就行。',
    tone: 'annoyed',
    lines: [
      '姜小满尝了一口，脸皱成一团：“坏了坏了，盐放多了！”',
      '你刚想安慰，她已经抓起醋瓶：“咸了加点醋就行，还有救。来，你也尝——火火火！看火！”',
    ],
  },
  {
    id: 'jiangxiaoman-f2-many-bowls',
    npcId: 'jiangxiaoman',
    track: 'friendship',
    threshold: 50,
    title: '瞎接活',
    summary: '陈拾又替她接席。她骂完，还是开灶。',
    tone: 'annoyed',
    lines: [
      '姜小满围裙都没解，进门就嚷：“陈拾又替我瞎接活！我都忙不过来了！”',
      '嚷完她又往灶边冲：“今儿个有大席，来帮把手。一天忙到晚，啥时候是个头啊——先别愣着，坐这儿吧。吃辣不？”',
    ],
  },
  {
    id: 'jiangxiaoman-f3-written-recipes',
    npcId: 'jiangxiaoman',
    track: 'friendship',
    threshold: 90,
    title: '三坛',
    summary: '秋菜一到，她先腌上三坛，还教你别心急。',
    tone: 'warm',
    lines: [
      '秋菜刚卸下车，姜小满已经抱着空坛：“等秋菜一来，我先腌上三坛。”',
      '她把你按到坛边：“腌菜呢最怕心急啦，每一步都要慢慢来。丑菜切了做咸菜，香喷喷——你笑什么，真香！”',
    ],
  },
  {
    id: 'jiangxiaoman-r1-honest-taste',
    npcId: 'jiangxiaoman',
    track: 'romance',
    threshold: 30,
    title: '好啦',
    summary: '桂花糕出炉。她嘴里还粘着糖，话说得很利落。',
    tone: 'shy',
    lines: [
      '桂花糕刚出笼。姜小满塞给你一块：“好甜哦！……你刚才说什么来着？”',
      '你又说一遍。她拍掉手上的面粉，笑得很响：“好啦，我也喜欢你。”',
    ],
  },
  {
    id: 'jiangxiaoman-r2-your-turn',
    npcId: 'jiangxiaoman',
    track: 'romance',
    threshold: 70,
    title: '面头子',
    summary: '她给你尝小时候爱吃的面头，顺便把人留下来。',
    tone: 'warm',
    lines: [
      '姜小满端来一盘面头子：“你尝尝。我跟我哥小时候就爱吃这个。”',
      '你吃的时候她一直盯着：“今天想吃啥？……不对，我问的不是这个。反正你别走，正好这锅糕要出炉了，边吃边喝。”',
    ],
  },
  {
    id: 'jiangxiaoman-r3-kitchen-roster',
    npcId: 'jiangxiaoman',
    track: 'romance',
    threshold: 120,
    title: '锅放哪',
    summary: '她答应搬来。第一句就问锅放哪。',
    tone: 'warm',
    lines: [
      '姜小满扛着最大那口锅站在门口：“行啊！锅放哪？”',
      '安顿完她拍拍手：“调料罐别乱挪！红盖子那个尤其别碰。厨房里的菜……不，这回我天天做，不会撂到坏。”',
    ],
  },
  {
    id: 'chenshi-f1-unknown-origin',
    npcId: 'chenshi',
    track: 'friendship',
    threshold: 20,
    title: '保准有说法',
    summary: '便宜货摆出来。他笑着说保准有说法，还是收了摊布。',
    tone: 'neutral',
    lines: [
      '摊上摆着一只便宜得离谱的壶。陈拾敲敲补丁：“壶是补过两回，没补过可就不是这价儿了。”',
      '有人还想再砍。他嘿嘿一笑：“谈钱伤感情。——这么便宜？保准有说法。您悠着点。”',
    ],
  },
  {
    id: 'chenshi-f2-private-news',
    npcId: 'chenshi',
    track: 'friendship',
    threshold: 50,
    title: '不能说',
    summary: '他拉你说秘密，说完又怕你说出去。',
    tone: 'worried',
    lines: [
      '陈拾左右瞅瞅，凑过来：“告诉你个秘密..我跟你说，你可得保证不告诉其他人。”',
      '说完他又摆手：“那事儿我也不清楚，不能说不能说。除非你保证不说出去是我告诉你的。”',
    ],
  },
  {
    id: 'chenshi-f3-consignment-ledger',
    npcId: 'chenshi',
    track: 'friendship',
    threshold: 90,
    title: '家伙式儿',
    summary: '十里八乡他都熟。青禾的货、林初的木，都经他手。',
    tone: 'warm',
    lines: [
      '陈拾扛着一捆家伙进门：“这是青禾托我买的家伙式儿，一会儿给她送去。这木料林初准喜欢。”',
      '他拍拍胸口：“不是我吹，这十里八乡没有我不熟的。包在我陈拾身上。”',
    ],
  },
  {
    id: 'chenshi-r1-ask-first',
    npcId: 'chenshi',
    track: 'romance',
    threshold: 30,
    title: '赶集',
    summary: '他约你赶集。话说得随意，眼睛却盯着你的反应。',
    tone: 'shy',
    lines: [
      '陈拾把摊布一卷：“一起赶集去不？你来的正好！我一会儿就进货去，想要啥？”',
      '你还没答，他又补一句：“嗨，我也不是从小就爱说笑话，那不是为了吆喝生意吗。——去不去嘛。”',
    ],
  },
  {
    id: 'chenshi-r2-quiet-road',
    npcId: 'chenshi',
    track: 'romance',
    threshold: 70,
    title: '货真价实',
    summary: '漂亮话备了三套，最后只剩一句老实的。',
    tone: 'shy',
    lines: [
      '酒桌上陈拾忽然正色，又自己泄了气：“我本来备了三套漂亮话。算了，我喜欢您。货真价实。”',
      '说完他举起杯子：“走哇，喝酒去。——刚才那句不算吆喝啊。”',
    ],
  },
  {
    id: 'chenshi-r3-two-ledgers',
    npcId: 'chenshi',
    track: 'romance',
    threshold: 120,
    title: '成嘞',
    summary: '他答应搬来。绢花先塞给你，账本说以后再买。',
    tone: 'warm',
    lines: [
      '陈拾抱着箱子站在门口：“成嘞！都听你的。”随手掏出一朵绢花，“前阵子进了时兴的绢花，给你留了一个玩儿。”',
      '进屋他东瞅西瞅：“这个别扔，我还有用。这个也别扔！……得买个新账本了。乡里乡亲，赊个账怕啥的。”',
    ],
  },
  {
    id: 'linchu-f1-miscut-tenon',
    npcId: 'linchu',
    track: 'friendship',
    threshold: 20,
    title: '重做',
    summary: '差一点也不行。他说不行不行，得重做。',
    tone: 'annoyed',
    lines: [
      '榫头差一点。林初盯着看了很久，忽然摇头：“不行不行，得重做。”',
      '废料堆到一边，他才闷闷补一句：“木工是精细活，差一点都不行。……先别扔，我瞅瞅，兴许能改小摆件。”',
    ],
  },
  {
    id: 'linchu-f2-no-apology',
    npcId: 'linchu',
    track: 'friendship',
    threshold: 50,
    title: '小狗',
    summary: '他雕了个小狗塞给你，自己先不好意思。',
    tone: 'warm',
    lines: [
      '林初从围裙里掏出一块小小的木雕：“我雕了个小狗，给你。”',
      '你接住，他耳朵有点红：“我不会说话，还是和木头打交道省心。……你喜欢就好。”',
    ],
  },
  {
    id: 'linchu-f3-maker-mark',
    npcId: 'linchu',
    track: 'friendship',
    threshold: 90,
    title: '新椅子',
    summary: '他打了一把新椅子，非要你当场试坐。',
    tone: 'shy',
    lines: [
      '林初把椅子搬到你跟前：“给你打了一把新椅子，你试试。”',
      '你坐下，他蹲在旁边看腿稳不稳：“别急别急，都说慢工出细活。不稳我就改。——顺手的事，不用给钱。”',
    ],
  },
  {
    id: 'linchu-r1-honest-quote',
    npcId: 'linchu',
    track: 'romance',
    threshold: 30,
    title: '酱牛肉',
    summary: '天气好。他提着酱牛肉，邀你出去喝一顿。',
    tone: 'warm',
    lines: [
      '林初手上还沾着木屑：“今天天气不错，我打了两斤酱牛肉，咱们出去喝一顿？”',
      '走到半路他又停住，认真看你一眼：“我喜欢你。”说完先低头，“……走吧。”',
    ],
  },
  {
    id: 'linchu-r2-visible-repair',
    npcId: 'linchu',
    track: 'romance',
    threshold: 70,
    title: '喝茶',
    summary: '收工后他不会找话题，只会让你坐着歇会儿。',
    tone: 'warm',
    lines: [
      '天黑了。林初放下刨刀：“天黑了，收工咯。坐着歇会儿吧，喝口茶。”',
      '茶烫着，他忽然说：“早。我带了馍馍，你要吃吗？”——明明已经晚上了。他没改口，又切了半块馍馍递过来。',
    ],
  },
  {
    id: 'linchu-r3-two-benches',
    npcId: 'linchu',
    track: 'romance',
    threshold: 120,
    title: '收拾',
    summary: '你一开口，他就慌着去收拾工具箱。',
    tone: 'shy',
    lines: [
      '你话还没说完，林初眼睛亮了：“真的吗？我..我这就去收拾。”',
      '进门他先把凿子搁到显眼处：“小心手！……凿子给你留下了。我的也留下。都行。”',
    ],
  },
  {
    id: 'baizhi-f1-two-leaves',
    npcId: 'baizhi',
    track: 'friendship',
    threshold: 20,
    title: '别乱吃',
    summary: '你刚想尝，她一把按住：不认识的别乱吃呀。',
    tone: 'annoyed',
    lines: [
      '你捏着一朵野花正要往嘴里送。白芷“啪”地按住你手：“不认识的别乱吃呀！”',
      '看你愣住，她又把花翻过来：“这种……嗯，这种倒是能吃的。你尝尝。刚才吓到你啦？”',
    ],
  },
  {
    id: 'baizhi-f2-leave-half',
    npcId: 'baizhi',
    track: 'friendship',
    threshold: 50,
    title: '白芷',
    summary: '雨后采蘑菇回来，她指给你看：这棵就是白芷。',
    tone: 'shy',
    lines: [
      '白芷裤脚还沾着泥：“早呀！刚下过雨，我们去采蘑菇吧——啊，先看这个。”',
      '她蹲下指着一株草：“看，这棵就是白芷。”停一下，小声补一句，“跟我同名。嘿嘿。”',
    ],
  },
  {
    id: 'baizhi-f3-open-herbarium',
    npcId: 'baizhi',
    track: 'friendship',
    threshold: 90,
    title: '百草茶',
    summary: '她塞给你一杯百草茶，又忽然想起小满炒了她的草药。',
    tone: 'warm',
    lines: [
      '白芷端来两碗：“尝尝我的百草茶。好茶好茶——橘皮也放了一点，你闻闻。”',
      '喝到一半她猛地拍桌：“你看小满，她竟然把我的草药炒了！o(╥﹏╥)o ……茶还能喝，别笑。”',
    ],
  },
  {
    id: 'baizhi-r1-clear-quiet',
    npcId: 'baizhi',
    track: 'romance',
    threshold: 30,
    title: '草籽',
    summary: '她凑近摘你头发上的草籽，话说得很轻。',
    tone: 'shy',
    lines: [
      '白芷忽然靠近：“你头发上粘草籽啦。我帮你摘。”',
      '摘完她手还停在半空：“我喜欢你。嘿嘿。”说完转身就跑，“天黑啦，别忙啦，快来吃饭吧！”',
    ],
  },
  {
    id: 'baizhi-r2-your-identification',
    npcId: 'baizhi',
    track: 'romance',
    threshold: 70,
    title: '漂亮虫',
    summary: '你肩上有只虫。她说好漂亮，顺便走神又把你喊回来。',
    tone: 'warm',
    lines: [
      '白芷眼睛一亮：“别动别动！你肩上有只虫，好漂亮。”小心捧走，放进小盒。',
      '抬头又愣住：“刚才走神了……你再说一遍好不好？——不是问虫。是问你刚才那句。”',
    ],
  },
  {
    id: 'baizhi-r3-quiet-hours',
    npcId: 'baizhi',
    track: 'romance',
    threshold: 120,
    title: '好漂亮呀',
    summary: '她答应搬来，先夸你家漂亮，再嘱咐药篓别揭开。',
    tone: 'warm',
    lines: [
      '白芷站在门口转了一圈：“好呀！你家好漂亮呀。”',
      '药篓刚放下她又叮嘱：“药篓别揭开，容易受潮。呀！有老鼠！！……骗你的。那我真的住下啦。”',
    ],
  },
  {
    id: 'suweiming-f1-recognized-story',
    npcId: 'suweiming',
    track: 'friendship',
    threshold: 20,
    title: '酸腐',
    summary: '有人笑他酸腐。他急了：读书人的事……',
    tone: 'annoyed',
    lines: [
      '代书摊前有人嘀咕酸腐。苏未名拂袖而起：“什么！什么酸腐！读书人的事...”',
      '说完又正了正袖口：“足下贵安？……咳，方才失态。小生这厢有礼了。”',
    ],
  },
  {
    id: 'suweiming-f2-on-time-letter',
    npcId: 'suweiming',
    track: 'friendship',
    threshold: 50,
    title: '孔方兄',
    summary: '谈钱时他叹一口气：读书人也逃不开孔方兄。',
    tone: 'annoyed',
    lines: [
      '苏未名算完代笔银两，叹气：“读书人也逃不开孔方兄啊。”',
      '见你看着他，他又立刻拱手：“兄台！别来无恙？小生今日抱恙，还请见谅——玩笑，玩笑。”',
    ],
  },
  {
    id: 'suweiming-f3-signed-collection',
    npcId: 'suweiming',
    track: 'friendship',
    threshold: 90,
    title: '好品味',
    summary: '你夸他文章，他得意得差点把自己夸进去。',
    tone: 'warm',
    lines: [
      '你随口夸了一句文采。苏未名眼睛亮了：“鄙人的文章？哎呀呀足下好品味！”',
      '随即掏出一卷：“见笑了，这是不才新作的文章。总有一天，我的文章会被人看见。”',
    ],
  },
  {
    id: 'suweiming-r1-no-metaphor',
    npcId: 'suweiming',
    track: 'romance',
    threshold: 30,
    title: '效力',
    summary: '他郑重拱手：小生不才，愿为足下效力。',
    tone: 'shy',
    lines: [
      '苏未名整了整衣襟，深施一礼：“小生不才，愿为足下效力。”',
      '礼还没完，他又小声补一句：“考了十年不中...给人写写信渡日也好。你若不应，当我没说。”',
    ],
  },
  {
    id: 'suweiming-r2-unwritten-page',
    npcId: 'suweiming',
    track: 'romance',
    threshold: 70,
    title: '半日闲',
    summary: '喝茶时他忽然文绉绉：浮生偷得半日闲。',
    tone: 'warm',
    lines: [
      '苏未名放下笔，举起茶杯：“浮生偷得半日闲。”',
      '你一笑，他耳朵红了：“好..这...好！不是夸茶。是……小生这厢有礼了。”',
    ],
  },
  {
    id: 'suweiming-r3-two-drawers',
    npcId: 'suweiming',
    track: 'romance',
    threshold: 120,
    title: '有礼了',
    summary: '答应搬来。进门先有礼，再咳着躲灰尘。',
    tone: 'warm',
    lines: [
      '苏未名抱着稿箱站在门口：“小生这厢有礼了。”',
      '进门扑面灰尘，他连咳带退：“咳咳咳，好大的灰尘。小生先行告退了——啊不是，是入住。后会有期了？不对，是相见甚欢。”',
    ],
  },
  {
    id: 'yueqingshan-f1-no-training',
    npcId: 'yueqingshan',
    track: 'friendship',
    threshold: 20,
    title: '打雷',
    summary: '雷越来越响。他说不是怕，是担心你。',
    tone: 'worried',
    lines: [
      '窗外雷一声比一声紧。岳青衫站得笔直，却连咳带喘：“咳咳..这雷...咳咳咳，怎么越来越响。”',
      '你看他一眼，他立刻抬高声音：“雷...我不是怕打雷！担心你怕而已。——确实，雷声怪吓人的。怕雷..很正常的，是吧？”',
    ],
  },
  {
    id: 'yueqingshan-f2-storm-list',
    npcId: 'yueqingshan',
    track: 'friendship',
    threshold: 50,
    title: '山狼',
    summary: '山里有狼。他不许你一个人去，话讲得很板。',
    tone: 'worried',
    lines: [
      '岳青衫把巡路图往墙上一按：“最近山里有狼出没，别一个人去。”',
      '说完又补一句：“可不敢告诉陈拾，回头全村都知道了。走快点，跟上。”',
    ],
  },
  {
    id: 'yueqingshan-f3-everyones-whistle',
    npcId: 'yueqingshan',
    track: 'friendship',
    threshold: 90,
    title: '小猫',
    summary: '他说今天没什么大事，只是从树上救下两只小猫。',
    tone: 'warm',
    lines: [
      '岳青衫怀里鼓鼓囊囊，神情却很正经：“今天没什么大事发生，从树上救下来两只小猫。”',
      '他掏出木哨晃了晃：“看，林初给我做了个木哨。最近怎么没看见你来锻炼？明日晨巡，出发。”',
    ],
  },
  {
    id: 'yueqingshan-r1-no-test',
    npcId: 'yueqingshan',
    track: 'romance',
    threshold: 30,
    title: '回答如下',
    summary: '他像汇报一样说喜欢你。',
    tone: 'shy',
    lines: [
      '你把话说完。岳青衫清了清嗓子，站得更直：“回答如下：我也喜欢你。”',
      '说完他耳朵红了，立刻岔开：“早点睡，不用等我。大晚上的别在外面溜达。”',
    ],
  },
  {
    id: 'yueqingshan-r2-different-pace',
    npcId: 'yueqingshan',
    track: 'romance',
    threshold: 70,
    title: '茶歇',
    summary: '他宣布茶歇无训练，却不懂你为什么笑。',
    tone: 'warm',
    lines: [
      '岳青衫把木剑搁到一边：“今日茶歇，无训练内容。你笑什么？”',
      '你继续笑。他闷闷喝了一口：“休息？我不知道闲下来该干什么。——豆袋保暖，便携用。我很喜欢。不是换话题。”',
    ],
  },
  {
    id: 'yueqingshan-r3-two-schedules',
    npcId: 'yueqingshan',
    track: 'romance',
    threshold: 120,
    title: '好',
    summary: '他答应搬来。就一个字，随即列队似的进门。',
    tone: 'warm',
    lines: [
      '岳青衫点头：“好。”顿了顿，又补一句，“好。”',
      '进门他把木剑靠墙：“巡路图我贴墙上了。库房怎么少了个箱子？……先不管。那就后会有期——不对，是住下了。”',
    ],
  },
  {
    id: 'wenjiu-f1-extra-key',
    npcId: 'wenjiu',
    track: 'friendship',
    threshold: 20,
    title: '过两天',
    summary: '又有人写过两天还。他冷着脸把账翻开。',
    tone: 'annoyed',
    lines: [
      '温九把账本往桌上一拍：“‘过两天还’不算数。两天又过两天，就坏账了。”',
      '见你看他，他哼一声：“铜钱我都数三遍。懒的人最爱说大概齐了。”',
    ],
  },
  {
    id: 'wenjiu-f2-wrong-memory',
    npcId: 'wenjiu',
    track: 'friendship',
    threshold: 50,
    title: '记岔了',
    summary: '账对不上。他先信账，后承认自己可能记岔了。',
    tone: 'worried',
    lines: [
      '温九对着两行数发愣：“这账对不上啊..我记得是三号，账上写五号。”',
      '他揉了揉眉心：“先按账上的查，我可能记岔了。人都说我记性好。越这么说，我越不敢忘。”',
    ],
  },
  {
    id: 'wenjiu-f3-public-key-ledger',
    npcId: 'wenjiu',
    track: 'friendship',
    threshold: 90,
    title: '公屋',
    summary: '公屋修缮入账。规矩他要写明白。',
    tone: 'warm',
    lines: [
      '温九在簿子上落笔：“公屋修缮记账一笔。屋顶别等漏了再修，早查早省钱。”',
      '写完他抬头：“你会不会觉得我烦？……问就问了。别光点头。”',
    ],
  },
  {
    id: 'wenjiu-r1-knock-first',
    npcId: 'wenjiu',
    track: 'romance',
    threshold: 30,
    title: '喜欢你',
    summary: '账合上了。他喝茶时忽然说喜欢你。',
    tone: 'shy',
    lines: [
      '温九把笔搁下：“账合上了，休息。喝茶。”',
      '沉默半盏茶，他盯着杯沿：“我喜欢你。”随即站起来，“桌上那封信，提醒你三回了，你看了没？”',
    ],
  },
  {
    id: 'wenjiu-r2-no-more-mention',
    npcId: 'wenjiu',
    track: 'romance',
    threshold: 70,
    title: '不提也罢',
    summary: '有人翻旧账。他拦一句：以前的事不提也罢。',
    tone: 'warm',
    lines: [
      '席间有人提起旧事。温九打断：“以前的事不提也罢。”',
      '散场后他跟你并肩走：“以前在大宅管账，东家忘了的事都来问我。有些事……记着也不必老说。”',
    ],
  },
  {
    id: 'wenjiu-r3-one-house-key',
    npcId: 'wenjiu',
    track: 'romance',
    threshold: 120,
    title: '多配一把',
    summary: '他答应搬来。先说钥匙，再说账两清。',
    tone: 'warm',
    lines: [
      '温九点头：“好。家门钥匙我去多配一把。”又改口，“好。钥匙我多配了一把。”',
      '进门看见靴子横在路上，他先啧一声：“你怎么又乱扔靴子。——账本在左边抽屉。别乱翻。”',
    ],
  },
  {
    id: 'hedeng-f1-retrieved-lamps',
    npcId: 'hedeng',
    track: 'friendship',
    threshold: 20,
    title: '捞灯',
    summary: '放灯节后，她拉你去下游捞湿透的灯。',
    tone: 'warm',
    lines: [
      '天亮后，河灯卷起裤脚往下游跑：“快来快来！别让泡烂的纸留给鱼。”',
      '捞上来一堆歪灯骨，她蹲着拆蜡，忽然抬头：“嘻嘻，这盏像蛤蟆。你猜哪盏本来想做兔子？”',
    ],
  },
  {
    id: 'hedeng-f2-unnamed-lamp',
    npcId: 'hedeng',
    track: 'friendship',
    threshold: 50,
    title: '怕黑',
    summary: '有人不要写名字。她也不追问，只偷偷说自己怕黑。',
    tone: 'shy',
    lines: [
      '来客只要一盏空白纸灯，说不想写名字。河灯点点头，把灯放进水里，一句也不多问。',
      '人走后她凑过来：“告诉你个秘密，其实我小时候最怕黑。现在也有点怕啦。”',
    ],
  },
  {
    id: 'hedeng-f3-path-lights',
    npcId: 'hedeng',
    track: 'friendship',
    threshold: 90,
    title: '十六盏',
    summary: '二里沟路灯装齐了。她边数边哼歌。',
    tone: 'warm',
    lines: [
      '二里沟的路灯一盏盏亮起来。河灯提着油壶走过去，嘴里数：“……十四、十五、十六！”',
      '她回头冲你挥手：“啦啦啦——亮起来啦！明天再给沈渡做船灯。不干啦？骗你的，再干一会儿。”',
    ],
  },
  {
    id: 'hedeng-r1-no-symbol',
    npcId: 'hedeng',
    track: 'romance',
    threshold: 30,
    title: '喜欢你',
    summary: '她写了好长一段，最后只说喜欢你。',
    tone: 'shy',
    lines: [
      '河灯把一张写满字的纸对着你晃了晃，又飞快折起来：“我本来写了好长一段...算了——我喜欢你。”',
      '说完她捂住脸，脚尖在地上点两下：“你先回答！别光看月亮。”',
    ],
  },
  {
    id: 'hedeng-r2-daylight-meeting',
    npcId: 'hedeng',
    track: 'romance',
    threshold: 70,
    title: '放风筝',
    summary: '大白天，她拉你去放风筝，灯一盏都没带。',
    tone: 'warm',
    lines: [
      '正午的河边没有灯可点。河灯抱着一只歪歪扭扭的纸鸢跑过来：“要去放风筝吗？”',
      '线扯断两次，她仍笑得很大声：“白天也好玩嘛！晚上再点灯——啊，茶还热吗？我又忘时间了。”',
    ],
  },
  {
    id: 'hedeng-r3-two-window-lamps',
    npcId: 'hedeng',
    track: 'romance',
    threshold: 120,
    title: '歪头鹅',
    summary: '她搬来了，窗台上先摆上两盏歪头鹅。',
    tone: 'warm',
    lines: [
      '河灯进门就把两盏歪头鹅往窗台一搁：“嘻嘻，这盏歪头鹅灯你喜欢吗？另一盏也是！”',
      '箱子打开像比说的多。她拍手：“好啊好啊！天啊，我好期待。——别扔别扔，那些练手的我还有用呢。”',
    ],
  },
  {
    id: 'taotao-f1-crooked-rabbit',
    npcId: 'taotao',
    track: 'friendship',
    threshold: 20,
    title: '凤凰',
    summary: '她画的凤凰又被认成小鸡。她不服。',
    tone: 'annoyed',
    lines: [
      '集上有个娃指着摊上那只金翅糖画喊小鸡。桃桃差点把铜勺摔了。',
      '“什么小鸡！我画的是凤凰！”她把糖画塞给你，“你说，像不像？不像也得说像。”',
    ],
  },
  {
    id: 'taotao-f2-sugar-thread',
    npcId: 'taotao',
    track: 'friendship',
    threshold: 50,
    title: '张二丫',
    summary: '娃们舔糖浆，她又骂又给。二丫她娘却不让来了。',
    tone: 'worried',
    lines: [
      '张大丫张二丫围着糖锅转。桃桃又嚷又递签：“不要再舔糖浆了！这根给你们。”',
      '过几天她闷闷的：“二丫她娘不让她来了，说糖吃多了虫牙。”停一下，又塞你一根，“你牙齿好，替她吃。”',
    ],
  },
  {
    id: 'taotao-f3-wall-of-rabbits',
    npcId: 'taotao',
    track: 'friendship',
    threshold: 90,
    title: '大车',
    summary: '生意好的那天，她拉你搓顿好的，嘴里全是阳棚大车。',
    tone: 'warm',
    lines: [
      '今天摊子卖空了。桃桃拉着你就走：“生意可好了！咱们去搓顿好的。”',
      '吃到一半她拍桌子：“等我有钱了，要换个带阳棚的大车！镇上的娃都得知道我桃桃的糖画！”',
    ],
  },
  {
    id: 'taotao-r1-best-rabbit',
    npcId: 'taotao',
    track: 'romance',
    threshold: 30,
    title: '糖兔子',
    summary: '她塞给你一只糖兔子，说是专门做的。',
    tone: 'shy',
    lines: [
      '收摊后桃桃忽然喊你，手里举着一只耳朵不太对称的糖兔子。',
      '“亲亲——给你做的！”她自己先笑出声，“歪了点。甜的。快吃，别化了。”',
    ],
  },
  {
    id: 'taotao-r2-sweet-half',
    npcId: 'taotao',
    track: 'romance',
    threshold: 70,
    title: '首饰店',
    summary: '嫂子生辰快到了。她拉你去逛首饰店，又不好意思说全。',
    tone: 'warm',
    lines: [
      '收摊以后桃桃拽住你袖子：“嗨，这算什么。嫂子画的龙才叫传神……陪我去逛逛首饰店吧，嫂子生辰快到了。”',
      '店里她东挑西看，忽然把一件小的推到你面前：“这个……不是给嫂子的。你别多想！多想也可以。”',
    ],
  },
  {
    id: 'taotao-r3-window-rabbit',
    npcId: 'taotao',
    track: 'romance',
    threshold: 120,
    title: '留座',
    summary: '小车推进院子。她给你留了个座，东西塞了你一怀。',
    tone: 'shy',
    lines: [
      '你话还没说完，桃桃已经蹦起来：“你终于问我啦！拿上这个，这个，这个。走！”',
      '小车推进院里，她拍拍边上窄板：“来，坐这儿。这个专门给你留的座。喜欢你❤”',
    ],
  },
] as const

export function eventsForNpc(npcId: string): readonly RelationshipEvent[] {
  return RELATIONSHIP_EVENTS.filter((event) => event.npcId === npcId)
}

export function eligibleEventIds(
  npcId: string,
  progress: NpcProgress,
): string[] {
  return eventsForNpc(npcId)
    .filter((event) =>
      event.track === 'friendship'
        ? progress.friendshipPoints >= event.threshold
        : progress.romanceUnlocked &&
          progress.romancePoints >= event.threshold,
    )
    .map((event) => event.id)
}

export function eventById(id: string): RelationshipEvent | undefined {
  return RELATIONSHIP_EVENTS.find((event) => event.id === id)
}

export function illustrationForEvent(
  event: RelationshipEvent,
): string | undefined {
  return EVENT_ILLUSTRATIONS[event.npcId]?.[event.track]
}
